server:
  port: ${PORT:8080}

spring:
  application:
    name: final

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:portfolio}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
    # Secret key para firmar tokens (EN PRODUCCIÓN USAR VARIABLE DE ENTORNO)
    secret: ${JWT_SECRET:ByWLZcz8oMpSh+1iMi8COSy8RT+V/2aXXmMUtVfTE1UH+EYdZa8NkvmajGAggHm/A85GK7Wh1gX5oK1f1PwYOA11}
    
    # Tiempo de expiración del access token (30 minutos)
    expiration: 1800000  # 30 minutos en milisegundos
    
    # Tiempo de expiración del refresh token (7 días)
    refresh-expiration: 604800000  # 7 días en milisegundos
    
    # Issuer del token
    issuer: FinalApplication-api
    
    # Header donde se envía el token
    header: Authorization
    
    # Prefijo del token
    prefix: "Bearer "